"""initial schema

Revision ID: f8916a41fe9a
Revises: 
Create Date: 2026-08-08 14:09:17.652642+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

revision: str = 'f8916a41fe9a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('company_domain', sa.String(length=255), nullable=True),
    sa.Column('career_page_url', sa.String(length=1000), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='companypriority', native_enum=False, length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scan_status', sa.String(length=40), nullable=True),
    sa.Column('hiring_activity_score', sa.Float(), nullable=False),
    sa.Column('hiring_activity_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'normalized_name', name='uq_company_user_normalized_name')
    )
    op.create_index(op.f('ix_companies_active'), 'companies', ['active'], unique=False)
    op.create_index(op.f('ix_companies_company_domain'), 'companies', ['company_domain'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_is_demo'), 'companies', ['is_demo'], unique=False)
    op.create_index(op.f('ix_companies_normalized_name'), 'companies', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_companies_user_id'), 'companies', ['user_id'], unique=False)
    op.create_table('scoring_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('job_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hiring_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recruiter_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outreach_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_scoring_config_user_name')
    )
    op.create_index(op.f('ix_scoring_configs_user_id'), 'scoring_configs', ['user_id'], unique=False)
    op.create_table('taxonomy_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('ROLE', 'INDUSTRY', 'SKILL', 'LOCATION', 'SENIORITY', 'EXCLUDE', name='taxonomykind', native_enum=False, length=20), nullable=False),
    sa.Column('term', sa.String(length=120), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'term', name='uq_taxonomy_user_kind_term')
    )
    op.create_index(op.f('ix_taxonomy_terms_kind'), 'taxonomy_terms', ['kind'], unique=False)
    op.create_index(op.f('ix_taxonomy_terms_user_id'), 'taxonomy_terms', ['user_id'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('headline', sa.String(length=300), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('resume_filename', sa.String(length=300), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('collector', sa.String(length=80), nullable=False),
    sa.Column('source', sa.Enum('CAREER_PAGE', 'CAREER_PAGE_JSONLD', 'GREENHOUSE_PUBLIC_API', 'LEVER_PUBLIC_API', 'ASHBY_PUBLIC_API', 'PUBLIC_JOB_FEED', 'COMPANY_TEAM_PAGE', 'JOB_POSTING_CONTACT', 'PATTERN_INFERENCE', 'MANUAL_ENTRY', 'DEMO_SEED', name='sourcetype', native_enum=False, length=40), nullable=False),
    sa.Column('target_url', sa.String(length=1000), nullable=True),
    sa.Column('trigger', sa.Enum('MANUAL', 'SCHEDULED', 'SEED', name='crawltrigger', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', 'BLOCKED', 'SKIPPED', name='crawlstatus', native_enum=False, length=20), nullable=False),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('records_added', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('bytes_downloaded', sa.Integer(), nullable=False),
    sa.Column('rate_limit_waits', sa.Integer(), nullable=False),
    sa.Column('rate_limit_seconds', sa.Float(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_runs_company_id'), 'crawl_runs', ['company_id'], unique=False)
    op.create_index(op.f('ix_crawl_runs_status'), 'crawl_runs', ['status'], unique=False)
    op.create_index('ix_crawl_started', 'crawl_runs', ['started_at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('normalized_title', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('normalized_location', sa.String(length=300), nullable=True),
    sa.Column('employment_type', sa.String(length=80), nullable=True),
    sa.Column('job_url', sa.String(length=1000), nullable=False),
    sa.Column('canonical_url', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.Enum('CAREER_PAGE', 'CAREER_PAGE_JSONLD', 'GREENHOUSE_PUBLIC_API', 'LEVER_PUBLIC_API', 'ASHBY_PUBLIC_API', 'PUBLIC_JOB_FEED', 'COMPANY_TEAM_PAGE', 'JOB_POSTING_CONTACT', 'PATTERN_INFERENCE', 'MANUAL_ENTRY', 'DEMO_SEED', name='sourcetype', native_enum=False, length=40), nullable=False),
    sa.Column('source_job_id', sa.String(length=200), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'STALE', 'UNKNOWN', name='jobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('relevance_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relevance_scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'canonical_url', name='uq_job_company_canonical_url')
    )
    op.create_index('ix_job_content_hash', 'jobs', ['company_id', 'content_hash'], unique=False)
    op.create_index('ix_job_discovered_at', 'jobs', ['discovered_at'], unique=False)
    op.create_index('ix_job_relevance', 'jobs', ['relevance_score'], unique=False)
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_jobs_is_demo'), 'jobs', ['is_demo'], unique=False)
    op.create_index(op.f('ix_jobs_normalized_title'), 'jobs', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_jobs_posted_at'), 'jobs', ['posted_at'], unique=False)
    op.create_table('recruiters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('professional_profile_url', sa.String(length=1000), nullable=True),
    sa.Column('public_professional_email', sa.String(length=320), nullable=True),
    sa.Column('email_source_url', sa.String(length=1000), nullable=True),
    sa.Column('email_source_type', sa.Enum('CAREER_PAGE', 'CAREER_PAGE_JSONLD', 'GREENHOUSE_PUBLIC_API', 'LEVER_PUBLIC_API', 'ASHBY_PUBLIC_API', 'PUBLIC_JOB_FEED', 'COMPANY_TEAM_PAGE', 'JOB_POSTING_CONTACT', 'PATTERN_INFERENCE', 'MANUAL_ENTRY', 'DEMO_SEED', name='sourcetype', native_enum=False, length=40), nullable=True),
    sa.Column('email_confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NONE', name='emailconfidence', native_enum=False, length=20), nullable=False),
    sa.Column('email_confidence_score', sa.Float(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_status', sa.Enum('VALID', 'INVALID', 'RISKY', 'UNKNOWN', 'NOT_CHECKED', name='verificationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_relevance', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('relevance_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relevance_scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('do_not_contact', sa.Boolean(), nullable=False),
    sa.Column('do_not_contact_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'normalized_name', name='uq_recruiter_company_name')
    )
    op.create_index('ix_recruiter_relevance', 'recruiters', ['relevance_score'], unique=False)
    op.create_index(op.f('ix_recruiters_company_id'), 'recruiters', ['company_id'], unique=False)
    op.create_index(op.f('ix_recruiters_do_not_contact'), 'recruiters', ['do_not_contact'], unique=False)
    op.create_index(op.f('ix_recruiters_is_demo'), 'recruiters', ['is_demo'], unique=False)
    op.create_index(op.f('ix_recruiters_normalized_name'), 'recruiters', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_recruiters_public_professional_email'), 'recruiters', ['public_professional_email'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.Enum('EMAIL', 'PROFILE_URL', 'APPLICATION_FORM', name='contacttype', native_enum=False, length=30), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('source_type', sa.Enum('CAREER_PAGE', 'CAREER_PAGE_JSONLD', 'GREENHOUSE_PUBLIC_API', 'LEVER_PUBLIC_API', 'ASHBY_PUBLIC_API', 'PUBLIC_JOB_FEED', 'COMPANY_TEAM_PAGE', 'JOB_POSTING_CONTACT', 'PATTERN_INFERENCE', 'MANUAL_ENTRY', 'DEMO_SEED', name='sourcetype', native_enum=False, length=40), nullable=False),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NONE', name='emailconfidence', native_enum=False, length=20), nullable=False),
    sa.Column('is_inferred', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recruiter_id', 'contact_type', 'value', name='uq_contact_unique_value')
    )
    op.create_index(op.f('ix_contacts_recruiter_id'), 'contacts', ['recruiter_id'], unique=False)
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'INVALID', 'RISKY', 'UNKNOWN', 'NOT_CHECKED', name='verificationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_email_verifications_recruiter_id'), 'email_verifications', ['recruiter_id'], unique=False)
    op.create_index('ix_verification_email_checked', 'email_verifications', ['email', 'checked_at'], unique=False)
    op.create_table('hiring_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.Enum('NEW_JOB', 'FRESH_JOB', 'MULTIPLE_OPENINGS', 'RECRUITER_IDENTIFIED', 'CAREER_PAGE_ACTIVITY', 'HIGH_RELEVANCE_ROLE', name='signaltype', native_enum=False, length=40), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hiring_signals_company_id'), 'hiring_signals', ['company_id'], unique=False)
    op.create_index(op.f('ix_hiring_signals_detected_at'), 'hiring_signals', ['detected_at'], unique=False)
    op.create_index(op.f('ix_hiring_signals_job_id'), 'hiring_signals', ['job_id'], unique=False)
    op.create_index('ix_signal_company_detected', 'hiring_signals', ['company_id', 'detected_at'], unique=False)
    op.create_table('job_recruiter_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.Enum('POSTED_BY', 'COMPANY_TALENT_TEAM', 'FUNCTION_MATCH', 'LISTED_CONTACT', name='recruiterrelation', native_enum=False, length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'recruiter_id', name='uq_job_recruiter')
    )
    op.create_index(op.f('ix_job_recruiter_relationships_job_id'), 'job_recruiter_relationships', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_recruiter_relationships_recruiter_id'), 'job_recruiter_relationships', ['recruiter_id'], unique=False)
    op.create_table('outreach_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'REVIEWED', 'APPROVED', 'CONTACTED', 'REPLIED', 'FOLLOW_UP', 'ARCHIVED', 'DO_NOT_CONTACT', name='outreachstatus', native_enum=False, length=30), nullable=False),
    sa.Column('outreach_priority', sa.Float(), nullable=False),
    sa.Column('priority_band', sa.String(length=40), nullable=True),
    sa.Column('priority_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('draft_subject', sa.String(length=400), nullable=True),
    sa.Column('draft_body', sa.Text(), nullable=True),
    sa.Column('draft_model', sa.String(length=120), nullable=True),
    sa.Column('draft_provider', sa.String(length=60), nullable=True),
    sa.Column('draft_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('draft_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('draft_approved', sa.Boolean(), nullable=False),
    sa.Column('draft_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_count', sa.Integer(), nullable=False),
    sa.Column('response_status', sa.Enum('AWAITING', 'POSITIVE', 'NEGATIVE', 'NO_RESPONSE', name='responsestatus', native_enum=False, length=30), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recruiter_id', 'job_id', name='uq_lead_recruiter_job')
    )
    op.create_index('ix_lead_status_priority', 'outreach_leads', ['status', 'outreach_priority'], unique=False)
    op.create_index(op.f('ix_outreach_leads_company_id'), 'outreach_leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_outreach_leads_job_id'), 'outreach_leads', ['job_id'], unique=False)
    op.create_index(op.f('ix_outreach_leads_recruiter_id'), 'outreach_leads', ['recruiter_id'], unique=False)
    op.create_index(op.f('ix_outreach_leads_status'), 'outreach_leads', ['status'], unique=False)
    op.create_index(op.f('ix_outreach_leads_user_id'), 'outreach_leads', ['user_id'], unique=False)
    op.create_table('source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_run_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=40), nullable=False),
    sa.Column('source_type', sa.Enum('CAREER_PAGE', 'CAREER_PAGE_JSONLD', 'GREENHOUSE_PUBLIC_API', 'LEVER_PUBLIC_API', 'ASHBY_PUBLIC_API', 'PUBLIC_JOB_FEED', 'COMPANY_TEAM_PAGE', 'JOB_POSTING_CONTACT', 'PATTERN_INFERENCE', 'MANUAL_ENTRY', 'DEMO_SEED', name='sourcetype', native_enum=False, length=40), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('reject_reason', sa.String(length=300), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_record_hash', 'source_records', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_records_crawl_run_id'), 'source_records', ['crawl_run_id'], unique=False)
    op.create_table('outreach_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('LEAD_CREATED', 'STATUS_CHANGED', 'DRAFT_GENERATED', 'DRAFT_EDITED', 'DRAFT_APPROVED', 'CONTACT_RECORDED', 'RESPONSE_RECORDED', 'NOTE_ADDED', 'DO_NOT_CONTACT_SET', 'EMAIL_VERIFIED', name='outreacheventtype', native_enum=False, length=40), nullable=False),
    sa.Column('from_status', sa.Enum('NEW', 'REVIEWED', 'APPROVED', 'CONTACTED', 'REPLIED', 'FOLLOW_UP', 'ARCHIVED', 'DO_NOT_CONTACT', name='outreachstatus', native_enum=False, length=30), nullable=True),
    sa.Column('to_status', sa.Enum('NEW', 'REVIEWED', 'APPROVED', 'CONTACTED', 'REPLIED', 'FOLLOW_UP', 'ARCHIVED', 'DO_NOT_CONTACT', name='outreachstatus', native_enum=False, length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['outreach_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_events_created_at'), 'outreach_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_outreach_events_lead_id'), 'outreach_events', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_events_lead_id'), table_name='outreach_events')
    op.drop_index(op.f('ix_outreach_events_created_at'), table_name='outreach_events')
    op.drop_table('outreach_events')
    op.drop_index(op.f('ix_source_records_crawl_run_id'), table_name='source_records')
    op.drop_index('ix_source_record_hash', table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_outreach_leads_user_id'), table_name='outreach_leads')
    op.drop_index(op.f('ix_outreach_leads_status'), table_name='outreach_leads')
    op.drop_index(op.f('ix_outreach_leads_recruiter_id'), table_name='outreach_leads')
    op.drop_index(op.f('ix_outreach_leads_job_id'), table_name='outreach_leads')
    op.drop_index(op.f('ix_outreach_leads_company_id'), table_name='outreach_leads')
    op.drop_index('ix_lead_status_priority', table_name='outreach_leads')
    op.drop_table('outreach_leads')
    op.drop_index(op.f('ix_job_recruiter_relationships_recruiter_id'), table_name='job_recruiter_relationships')
    op.drop_index(op.f('ix_job_recruiter_relationships_job_id'), table_name='job_recruiter_relationships')
    op.drop_table('job_recruiter_relationships')
    op.drop_index('ix_signal_company_detected', table_name='hiring_signals')
    op.drop_index(op.f('ix_hiring_signals_job_id'), table_name='hiring_signals')
    op.drop_index(op.f('ix_hiring_signals_detected_at'), table_name='hiring_signals')
    op.drop_index(op.f('ix_hiring_signals_company_id'), table_name='hiring_signals')
    op.drop_table('hiring_signals')
    op.drop_index('ix_verification_email_checked', table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_recruiter_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_contacts_recruiter_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_recruiters_public_professional_email'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_normalized_name'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_is_demo'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_do_not_contact'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_company_id'), table_name='recruiters')
    op.drop_index('ix_recruiter_relevance', table_name='recruiters')
    op.drop_table('recruiters')
    op.drop_index(op.f('ix_jobs_posted_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_normalized_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_demo'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_index('ix_job_relevance', table_name='jobs')
    op.drop_index('ix_job_discovered_at', table_name='jobs')
    op.drop_index('ix_job_content_hash', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_crawl_started', table_name='crawl_runs')
    op.drop_index(op.f('ix_crawl_runs_status'), table_name='crawl_runs')
    op.drop_index(op.f('ix_crawl_runs_company_id'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_taxonomy_terms_user_id'), table_name='taxonomy_terms')
    op.drop_index(op.f('ix_taxonomy_terms_kind'), table_name='taxonomy_terms')
    op.drop_table('taxonomy_terms')
    op.drop_index(op.f('ix_scoring_configs_user_id'), table_name='scoring_configs')
    op.drop_table('scoring_configs')
    op.drop_index(op.f('ix_companies_user_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_normalized_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_demo'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_domain'), table_name='companies')
    op.drop_index(op.f('ix_companies_active'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
